[cosmic-ray]
# Subject Under Test
module-path = "benchmark/validation.py"
test-command = "env PYTHONPATH=.:benchmark pytest tests/"

# Timeout per evitare loop infiniti causati da mutanti "cattivi"
timeout = 10.0

# Aggiungi questa sezione per dire a Cosmic Ray di eseguire i test localmente
[cosmic-ray.distributor]
name = "local"
