# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import triangle as module_0


def test_case_0():
    int_0 = -463
    var_0 = module_0.classify_triangle(int_0, int_0, int_0)
    assert var_0 == "Invalid"


def test_case_1():
    int_0 = 2236
    var_0 = module_0.classify_triangle(int_0, int_0, int_0)
    assert var_0 == "Equilateral"


def test_case_2():
    int_0 = 84
    int_1 = -1685
    var_0 = module_0.classify_triangle(int_0, int_1, int_0)
    assert var_0 == "Invalid"


def test_case_3():
    int_0 = 1510
    float_0 = -428.0
    var_0 = module_0.classify_triangle(int_0, int_0, float_0)
    assert var_0 == "Invalid"
    var_1 = module_0.classify_triangle(int_0, int_0, int_0)
    assert var_1 == "Equilateral"


def test_case_4():
    int_0 = 85
    int_1 = 32
    var_0 = module_0.classify_triangle(int_1, int_1, int_0)
    assert var_0 == "Not a Triangle"


def test_case_5():
    int_0 = 44
    int_1 = 573
    var_0 = module_0.classify_triangle(int_0, int_1, int_0)
    assert var_0 == "Not a Triangle"


def test_case_6():
    int_0 = 85
    int_1 = 32
    var_0 = module_0.classify_triangle(int_0, int_1, int_1)
    assert var_0 == "Not a Triangle"
    var_1 = module_0.classify_triangle(int_1, int_1, int_0)
    assert var_1 == "Not a Triangle"


def test_case_7():
    int_0 = 1666
    int_1 = 2249
    var_0 = module_0.classify_triangle(int_0, int_1, int_0)
    assert var_0 == "Isosceles"


def test_case_8():
    int_0 = 324
    bool_0 = True
    var_0 = module_0.classify_triangle(int_0, int_0, bool_0)
    assert var_0 == "Isosceles"


def test_case_9():
    int_0 = 109
    int_1 = 36
    var_0 = module_0.classify_triangle(int_1, int_0, int_0)
    assert var_0 == "Isosceles"
