# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import triangle as module_0


def test_case_0():
    bool_0 = False
    none_type_0 = None
    var_0 = module_0.classify_triangle(bool_0, none_type_0, none_type_0)
    assert var_0 == "Invalid"
    int_0 = 1543
    var_1 = module_0.classify_triangle(int_0, bool_0, bool_0)
    assert var_1 == "Invalid"


def test_case_1():
    bool_0 = True
    var_0 = module_0.classify_triangle(bool_0, bool_0, bool_0)
    assert var_0 == "Equilateral"


def test_case_2():
    bool_0 = True
    float_0 = 677.7
    var_0 = module_0.classify_triangle(bool_0, float_0, float_0)
    assert var_0 == "Isosceles"


def test_case_3():
    bool_0 = False
    int_0 = 1543
    var_0 = module_0.classify_triangle(int_0, bool_0, bool_0)
    assert var_0 == "Invalid"


def test_case_4():
    bool_0 = True
    int_0 = 1543
    var_0 = module_0.classify_triangle(int_0, bool_0, bool_0)
    assert var_0 == "Not a Triangle"


def test_case_5():
    bool_0 = False
    var_0 = module_0.classify_triangle(bool_0, bool_0, bool_0)
    assert var_0 == "Invalid"
    bool_1 = True
    var_1 = module_0.classify_triangle(bool_1, bool_1, bool_0)
    assert var_1 == "Invalid"


def test_case_6():
    bool_0 = True
    var_0 = module_0.classify_triangle(bool_0, bool_0, bool_0)
    assert var_0 == "Equilateral"
    float_0 = 677.7
    var_1 = module_0.classify_triangle(bool_0, float_0, bool_0)
    assert var_1 == "Not a Triangle"


def test_case_7():
    bool_0 = True
    float_0 = 677.7
    var_0 = module_0.classify_triangle(bool_0, bool_0, float_0)
    assert var_0 == "Not a Triangle"
    var_1 = module_0.classify_triangle(float_0, bool_0, bool_0)
    assert var_1 == "Not a Triangle"


def test_case_8():
    bool_0 = True
    float_0 = 677.7
    var_0 = module_0.classify_triangle(float_0, float_0, bool_0)
    assert var_0 == "Isosceles"


def test_case_9():
    bool_0 = True
    float_0 = 677.7
    var_0 = module_0.classify_triangle(float_0, bool_0, float_0)
    assert var_0 == "Isosceles"


def test_case_10():
    float_0 = 711.8708494258533
    float_1 = 2090.386163
    float_2 = 2023.1234016290423
    var_0 = module_0.classify_triangle(float_1, float_2, float_0)
    assert var_0 == "Scalene"
