# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import example_math as module_0


def test_case_0():
    bool_0 = False
    bool_1 = True
    str_0 = module_0.triangle(bool_1, bool_1, bool_1)
    assert str_0 == "Equilateral"
    str_1 = module_0.triangle(bool_0, bool_0, bool_0)
    assert str_1 == "Invalid"


def test_case_1():
    int_0 = 1968
    bool_0 = True
    str_0 = module_0.triangle(int_0, bool_0, int_0)
    assert str_0 == "Isosceles"


def test_case_2():
    int_0 = 1960
    bool_0 = False
    str_0 = module_0.triangle(int_0, bool_0, int_0)
    assert str_0 == "Invalid"


def test_case_3():
    bool_0 = True
    str_0 = module_0.triangle(bool_0, bool_0, bool_0)
    assert str_0 == "Equilateral"
    int_0 = 279
    str_1 = module_0.triangle(bool_0, int_0, int_0)
    assert str_1 == "Isosceles"


def test_case_4():
    bool_0 = True
    int_0 = -1055
    bool_1 = True
    str_0 = module_0.triangle(bool_1, bool_1, bool_1)
    assert str_0 == "Equilateral"
    str_1 = module_0.triangle(bool_0, bool_1, int_0)
    assert str_1 == "Invalid"


def test_case_5():
    float_0 = 1279.9998
    bool_0 = True
    str_0 = module_0.triangle(bool_0, float_0, bool_0)
    assert str_0 == "Invalid"
    str_1 = module_0.triangle(float_0, bool_0, bool_0)
    assert str_1 == "Invalid"
    bool_1 = True
    str_2 = module_0.triangle(bool_1, bool_1, bool_1)
    assert str_2 == "Equilateral"


def test_case_6():
    int_0 = 28
    bool_0 = True
    str_0 = module_0.triangle(int_0, int_0, bool_0)
    assert str_0 == "Isosceles"


def test_case_7():
    int_0 = 1988
    bool_0 = True
    str_0 = module_0.triangle(int_0, bool_0, int_0)
    assert str_0 == "Isosceles"
    str_1 = module_0.triangle(int_0, bool_0, bool_0)
    assert str_1 == "Invalid"


def test_case_8():
    bool_0 = True
    int_0 = 551
    str_0 = module_0.triangle(bool_0, bool_0, int_0)
    assert str_0 == "Invalid"


def test_case_9():
    int_0 = 1975
    bool_0 = True
    str_0 = module_0.triangle(int_0, bool_0, int_0)
    assert str_0 == "Isosceles"
    bool_1 = False
    str_1 = module_0.triangle(bool_1, bool_1, bool_1)
    assert str_1 == "Invalid"
    int_1 = 731
    int_2 = 1951
    str_2 = module_0.triangle(int_0, int_1, int_2)
    assert str_2 == "Scalene"
