# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import triangle as module_0 


def test_case_0():
    int_0 = -2496
    var_0 = module_0.classify_triangle(int_0, int_0, int_0)
    assert var_0 == "Invalid"


def test_case_1():
    bool_0 = True
    var_0 = module_0.classify_triangle(bool_0, bool_0, bool_0)
    assert var_0 == "Equilateral"


def test_case_2():
    int_0 = -2496
    bool_0 = True
    var_0 = module_0.classify_triangle(bool_0, int_0, bool_0)
    assert var_0 == "Invalid"
    var_1 = module_0.classify_triangle(int_0, int_0, int_0)
    assert var_1 == "Invalid"


def test_case_3():
    int_0 = -3136
    bool_0 = True
    var_0 = module_0.classify_triangle(bool_0, bool_0, int_0)
    assert var_0 == "Invalid"
    var_1 = module_0.classify_triangle(int_0, bool_0, bool_0)
    assert var_1 == "Invalid"
    var_2 = module_0.classify_triangle(bool_0, bool_0, bool_0)
    assert var_2 == "Equilateral"


def test_case_4():
    bool_0 = True
    int_0 = 1568
    var_0 = module_0.classify_triangle(bool_0, bool_0, int_0)
    assert var_0 == "Not a Triangle"
    var_1 = module_0.classify_triangle(bool_0, bool_0, bool_0)
    assert var_1 == "Equilateral"
    var_2 = module_0.classify_triangle(int_0, int_0, bool_0)
    assert var_2 == "Isosceles"


def test_case_5():
    bool_0 = True
    int_0 = 1562
    var_0 = module_0.classify_triangle(int_0, bool_0, bool_0)
    assert var_0 == "Not a Triangle"
    var_1 = module_0.classify_triangle(int_0, bool_0, int_0)
    assert var_1 == "Isosceles"


def test_case_6():
    bool_0 = True
    int_0 = 1568
    var_0 = module_0.classify_triangle(int_0, int_0, bool_0)
    assert var_0 == "Isosceles"


def test_case_7():
    bool_0 = True
    int_0 = 1545
    int_1 = 3939
    var_0 = module_0.classify_triangle(bool_0, int_1, int_0)
    assert var_0 == "Not a Triangle"


def test_case_8():
    int_0 = 1545
    int_1 = 1558
    var_0 = module_0.classify_triangle(int_0, int_1, int_1)
    assert var_0 == "Isosceles"


def test_case_9():
    bool_0 = True
    int_0 = 1534
    var_0 = module_0.classify_triangle(int_0, bool_0, int_0)
    assert var_0 == "Isosceles"
    int_1 = 1553
    float_0 = 610.8068
    var_1 = module_0.classify_triangle(int_0, float_0, int_1)
    assert var_1 == "Scalene"
